In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


### Creating tensors with tf.constant

In [26]:

scalar = tf.constant(value = 7, 
                     dtype = tf.float16, 
                     shape=None,
                    name = "First Tensor")
scalar

<tf.Tensor: shape=(), dtype=float16, numpy=7.0>

In [27]:
scalar.ndim

0

In [30]:
vector = tf.constant(value = [10, 10],
                     dtype = None,
                     shape = None
                    )
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [31]:
vector.ndim

1

In [32]:
matrix = tf.constant(value= [[10, 7],
                             [7, 10]],
                     dtype=None,
                     shape=None
                    )
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [34]:
matrix.ndim

2

In [41]:
another_matrix = tf.constant(value=[[10, 7],
                                     [7, 10],
                                    [5, 32]
                                   ],
                             dtype=tf.float32,
                             shape=None
                            )
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 5., 32.]], dtype=float32)>

In [40]:
another_matrix.ndim

2

In [44]:
tensor = tf.constant(value=[[[1, 2, 3],
                            [4, 5, 6]],

                           [[7, 8, 9],
                            [10, 11, 12]],

                           [[13, 14, 15],
                            [16, 17, 18]]],
                     dtype=None,
                     shape=None
                    )
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [47]:
tf.convert_to_tensor(7)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Creating tensors with tf.Variable

In [71]:
a = tf.constant([1, 2])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [72]:
b = tf.Variable([1, 2])
b

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [76]:
print(a == b)
print(a[0] == b[0])
print(a[1] == b[1])

tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)


In [77]:
# b[0] = 7
b[0].assign(100)
b

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,   2], dtype=int32)>

### Creating Random tensors

In [136]:
random_1 = tf.random.Generator.from_seed(seed=42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [137]:
random_2 =tf.random.Generator.from_seed(seed=42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [138]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle tensors (your data) the order of elements in a tensor

In [209]:
a = tf.constant([[10 , 32],
           [ 3, 4 ],
           [7, 8 ]]
           )
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 32],
       [ 3,  4],
       [ 7,  8]], dtype=int32)>

In [236]:
tf.random.set_seed(2)
tf.random.shuffle(a, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 3,  4],
       [10, 32]], dtype=int32)>

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.8.0'

In [5]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


2023-06-01 18:46:06.495060: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [45]:
@tf.function
def a():
    x1 = tf.random.uniform([1])
    x2 = tf.random.uniform([1])
    return x1, x2

@tf.function
def g():
    x1 = tf.random.uniform([1])
    x2 = tf.random.uniform([1])
    return x1, x2

print(a())
print(g())


(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


#### Other ways to make Tensors ( Numpy arrays )

In [49]:
tf.ones(shape = [7,7], dtype=tf.int32)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [50]:
tf.zeros(shape = [7,7], dtype=tf.int32)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [54]:
import numpy as np

np_a = np.array([7,7])
np_a

array([7, 7])

In [56]:
tf_a = tf.constant(np_a)
tf_a

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([7, 7])>

### Getting informations from Tensors (tensor attributes)

* Shape
* Rank (ndim)
* Size
* data type

### Indexing a Tensor

In [3]:
# Get first two elements from each dimention of a tensor

a = tf.random.uniform(shape=(2,3,4,5))
a

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.5537261 , 0.55138767, 0.4825313 , 0.34886026, 0.04898632],
         [0.8496057 , 0.46119344, 0.6366912 , 0.97059584, 0.699932  ],
         [0.2782017 , 0.36532962, 0.8340776 , 0.25935447, 0.6068921 ],
         [0.52604556, 0.7735275 , 0.49318302, 0.41069555, 0.700961  ]],

        [[0.61531985, 0.31299174, 0.34841406, 0.5465218 , 0.10421395],
         [0.91221726, 0.40148866, 0.65771747, 0.3995316 , 0.7634808 ],
         [0.07165873, 0.06656504, 0.24796593, 0.06011581, 0.6530814 ],
         [0.7165873 , 0.65184045, 0.06779146, 0.34036708, 0.22258663]],

        [[0.9053707 , 0.5259954 , 0.06761348, 0.5881655 , 0.29354393],
         [0.15228856, 0.28136277, 0.97459424, 0.8701937 , 0.58489287],
         [0.9386697 , 0.05878758, 0.8108885 , 0.08377218, 0.82529044],
         [0.92501354, 0.5047239 , 0.9390217 , 0.79709923, 0.38528752]]],


       [[[0.94280183, 0.17443287, 0.9585594 , 0.8718554 , 0.93480396],
         [0.148

In [28]:
for i in range(0,2):
    for j in range(0,3):
        for k in range(0,4):
            print(a[i][j][k][0:2].numpy())

[0.5537261  0.55138767]
[0.8496057  0.46119344]
[0.2782017  0.36532962]
[0.52604556 0.7735275 ]
[0.61531985 0.31299174]
[0.91221726 0.40148866]
[0.07165873 0.06656504]
[0.7165873  0.65184045]
[0.9053707 0.5259954]
[0.15228856 0.28136277]
[0.9386697  0.05878758]
[0.92501354 0.5047239 ]
[0.94280183 0.17443287]
[0.14864147 0.7992587 ]
[0.75261855 0.89434767]
[0.6590246  0.15261829]
[0.02358174 0.52492964]
[0.5516496  0.52863276]
[0.3745196 0.6369431]
[0.6687236 0.8709078]
[0.8125454 0.971043 ]
[0.6298442 0.7473053]
[0.26930344 0.18096101]
[0.23526049 0.14590907]


In [31]:
a[:2,:2,:2,:2].numpy()

array([[[[0.5537261 , 0.55138767],
         [0.8496057 , 0.46119344]],

        [[0.61531985, 0.31299174],
         [0.91221726, 0.40148866]]],


       [[[0.94280183, 0.17443287],
         [0.14864147, 0.7992587 ]],

        [[0.02358174, 0.52492964],
         [0.5516496 , 0.52863276]]]], dtype=float32)

In [32]:
a[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[0.5537261 , 0.55138767, 0.4825313 , 0.34886026, 0.04898632]]]],
      dtype=float32)>

In [47]:
b = tf.random.uniform(shape=(2,2,3))
b

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.85226274, 0.84929955, 0.13429987],
        [0.5024353 , 0.81800985, 0.41620457]],

       [[0.7848079 , 0.45099068, 0.9126837 ],
        [0.618937  , 0.84996045, 0.98594916]]], dtype=float32)>

In [55]:
b[:,:,-1]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.13429987, 0.41620457],
       [0.9126837 , 0.98594916]], dtype=float32)>

### Adding extra dimension to a given tensor (Reshaping)

In [56]:
b[...,tf.newaxis]

<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[0.85226274],
         [0.84929955],
         [0.13429987]],

        [[0.5024353 ],
         [0.81800985],
         [0.41620457]]],


       [[[0.7848079 ],
         [0.45099068],
         [0.9126837 ]],

        [[0.618937  ],
         [0.84996045],
         [0.98594916]]]], dtype=float32)>

In [61]:
b[:,:,tf.newaxis, :]

<tf.Tensor: shape=(2, 2, 1, 3), dtype=float32, numpy=
array([[[[0.85226274, 0.84929955, 0.13429987]],

        [[0.5024353 , 0.81800985, 0.41620457]]],


       [[[0.7848079 , 0.45099068, 0.9126837 ]],

        [[0.618937  , 0.84996045, 0.98594916]]]], dtype=float32)>

In [69]:
b[:,:,:,tf.newaxis]

<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[0.85226274],
         [0.84929955],
         [0.13429987]],

        [[0.5024353 ],
         [0.81800985],
         [0.41620457]]],


       [[[0.7848079 ],
         [0.45099068],
         [0.9126837 ]],

        [[0.618937  ],
         [0.84996045],
         [0.98594916]]]], dtype=float32)>

In [68]:
tf.expand_dims(b, axis=-1)

<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[0.85226274],
         [0.84929955],
         [0.13429987]],

        [[0.5024353 ],
         [0.81800985],
         [0.41620457]]],


       [[[0.7848079 ],
         [0.45099068],
         [0.9126837 ]],

        [[0.618937  ],
         [0.84996045],
         [0.98594916]]]], dtype=float32)>

In [72]:
tf.reshape(b, shape=(2,2,3,1))

<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[0.85226274],
         [0.84929955],
         [0.13429987]],

        [[0.5024353 ],
         [0.81800985],
         [0.41620457]]],


       [[[0.7848079 ],
         [0.45099068],
         [0.9126837 ]],

        [[0.618937  ],
         [0.84996045],
         [0.98594916]]]], dtype=float32)>

### Manipulating tensors (Tensor Operations)

#### Element wise operations

In [74]:
a = tf.random.uniform(shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.2841221 , 0.63239515],
       [0.7770313 , 0.7959813 ]], dtype=float32)>

In [75]:
a+7

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.284122 , 7.6323953],
       [7.7770314, 7.7959814]], dtype=float32)>

In [76]:
a*7

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.9888548, 4.426766 ],
       [5.439219 , 5.571869 ]], dtype=float32)>

In [77]:
a-7

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-6.715878 , -6.3676047],
       [-6.2229686, -6.2040186]], dtype=float32)>

In [79]:
tf.add(a,7)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.284122 , 7.6323953],
       [7.7770314, 7.7959814]], dtype=float32)>

In [80]:
tf.multiply(a,7)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.9888548, 4.426766 ],
       [5.439219 , 5.571869 ]], dtype=float32)>

In [81]:
tf.subtract(a,7)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-6.715878 , -6.3676047],
       [-6.2229686, -6.2040186]], dtype=float32)>

#### Matrix Multiplication

In [84]:
a = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]
                ])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [85]:
b = tf.constant([[3,5],
                 [6,7],
                 [1,8]
                ])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [86]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [89]:
a@b  # python way of matmul

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [90]:
tf.transpose(a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 7, 3],
       [2, 2, 3],
       [5, 1, 3]], dtype=int32)>

In [92]:
tf.reshape(a, shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

Transpose and Reshape are entirely different. 
Reshape is very dangeorus, as it is just shuffling the numbers to get the new given shape values.

While Transpose has systematic way of restructing the given matrix.

In [95]:
# Not very clear for me
tf.tensordot(a,b, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

### Changing Data Type of a Tensor

In [102]:
a = tf.constant([1.7,7.4])
print(a.dtype)
a

<dtype: 'float32'>


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [103]:
b = tf.constant([1,7])
print(b.dtype)
b

<dtype: 'int32'>


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

Based on the data which is inside the tensor, the data type will be decided. Default is `32 bit` of the given type.

In [104]:
tf.cast(a,dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [105]:
tf.cast(a,dtype=tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

We can change from `float32` to `int16` and wise versa as well

In [108]:
tf.cast(a,dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

### Aggregating Tensors

In [112]:
a = tf.random.normal(shape=(3,3),
                     mean=0,
                     stddev=-5)
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.304224  ,  0.64422756, -4.1128983 ],
       [-3.59131   ,  3.188889  , -1.1616077 ],
       [ 4.190223  , -3.5656834 ,  7.2298436 ]], dtype=float32)>

* Absolute values
* Minimum
* Maximum
* Mean
* Sum
* Positional Max (argmax)
* Positional Min (argmin)

In [113]:
# Get absolute Values
tf.abs(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[7.304224  , 0.64422756, 4.1128983 ],
       [3.59131   , 3.188889  , 1.1616077 ],
       [4.190223  , 3.5656834 , 7.2298436 ]], dtype=float32)>

In [231]:
import numpy as np
tf.random.set_seed(42)
a = tf.random.uniform(shape=(50,),
                    minval=1,
                      maxval=100,
                      dtype=tf.int32,
                      seed=42)

a

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([49, 47, 86, 72,  9, 89, 45, 99, 48, 86,  2, 76, 86, 61, 10, 55, 44,
       86, 89, 17,  7, 58,  7, 98, 57, 63, 40, 24, 48, 21, 92, 56, 20, 94,
       29, 40, 15,  4, 98, 28, 17, 50, 71, 29, 99, 58, 96, 38, 30, 34],
      dtype=int32)>

In [232]:
print("Shape of Given Tensor :" , a.shape)
print("Size of Given Tensor :" , tf.size(a).numpy())
print("Rank  of Given Tensor :" , a.ndim)
print("Data type of Given Tensor Elements :" , a.dtype)

Shape of Given Tensor : (50,)
Size of Given Tensor : 50
Rank  of Given Tensor : 1
Data type of Given Tensor Elements : <dtype: 'int32'>


In [233]:
tf.reduce_min(a).numpy()

2

In [234]:
tf.reduce_max(a).numpy()

99

In [235]:
tf.reduce_mean(a).numpy()

51

In [236]:
tf.reduce_sum(a).numpy()

2577

In [237]:
tf.math.reduce_variance(tf.cast(a,dtype=tf.float32)).numpy()

902.5284

In [239]:
tf.math.reduce_std(tf.cast(a,dtype=tf.float32)).numpy()

30.04211

In [241]:
tf.argmax(a).numpy()

7

In [243]:
tf.argmin(a).numpy()

10

### Squeeze a Tensor ( Remove 1 dimension from Tensor)

In [248]:
a = tf.random.uniform(shape=(1,2,3,1,1,5,1,1))
print(a.shape)
print(a.dtype)

(1, 2, 3, 1, 1, 5, 1, 1)
<dtype: 'float32'>


In [249]:
tf.squeeze(a)

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ],
        [0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384],
        [0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178]],

       [[0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018],
        [0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877],
        [0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155]]],
      dtype=float32)>

In [251]:
tf.squeeze(a).shape

TensorShape([2, 3, 5])

### One-Hot Encoding

In [262]:
li = ["red", "blue", "green", "purple", "red"]
li = [0,1,2,3,4,0]

tf.one_hot(li,depth=5,dtype=tf.int32)

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0]], dtype=int32)>

In [265]:
tf.one_hot(li,depth=5,on_value="Yes",off_value="No")

<tf.Tensor: shape=(6, 5), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'No', b'Yes'],
       [b'Yes', b'No', b'No', b'No', b'No']], dtype=object)>

### More Math operations

In [267]:
a = tf.range(1,10)
a

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

    * Squaring
    * Log
    * Square Root

In [268]:
tf.square(a)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [271]:
tf.sqrt(tf.cast(a,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [274]:
tf.math.log(tf.cast(a,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Compatiblity in between NP and TF

In [281]:
# They work together and have highest level of interactiosn
a = np.array([3,7,10])
print(type(a))
a

<class 'numpy.ndarray'>


array([ 3,  7, 10])

In [279]:
a = tf.constant(a)
print(type(a))
a

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 10])>

In [282]:
a = a.numpy()  #np.array(a)
print(type(a))
a

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

Default data type can be different between np and tf.
TF elements run on GPU but 
NP elements can only run in CPU.

### GPU usage

In [287]:
tf.test.is_built_with_gpu_support()

False

In [285]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [288]:
tf.config.list_physical_devices("GPU")

[]

In [290]:
tf.test.is_built_with_cuda()

False

In [ ]:
!nvidia-smi